# Generated by Django 5.0.6 on 2024-06-09 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createlocal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='local',
            name='last_login',
        ),
    ]
